/**
 * Created by caixiaowei on 17/10/24.
 */

/**
 * 页面跳转
 */
//登录页面
export const NAVIGATOR_LOGIN = "NAVIGATOR_LOGIN";

//注册页面
export const NAVIGATOR_REGISTER = "NAVIGATOR_REGISTER";

//注册协议页面
export const NAVIGATOR_AGREEMENT = "NAVIGATOR_AGREEMENT";

//注册密码页面
export const NAVIGATOR_REGISTER_PASSWORD = "NAVIGATOR_REGISTER_PASSWORD";

//创建企业页面
export const NAVIGATOR_OPEN_ENTERPRISE = "NAVIGATOR_OPEN_ENTERPRISE";

//创建企业带参数
export const NAVIGATOR_OPEN_ENTERPRISE_WITH_PARAMS = "NAVIGATOR_OPEN_ENTERPRISE_WITH_PARAMS";

//成功创建企业页面
export const NAVIGATOR_SUCCESS_OPEN_ENTERPRISE = "NAVIGATOR_SUCCESS_OPEN_ENTERPRISE";

//个人信息页面
export const NAVIGATOR_PERSONAL_INFORMATION = "NAVIGATOR_PERSONAL_INFORMATION";

//关于我们页面
export const NAVIGATOR_ABOUT_US = "NAVIGATOR_ABOUT_US";

//设置页面
export const NAVIGATOR_SET_UP = "NAVIGATOR_SET_UP";

//我的页面
export const NAVIGATOR_MINE = "NAVIGATOR_MINE";

//修改密码-手机验证码验证页面
export const NAVIGATOR_MODIFY_PASSWORD_VERIFICATION = "NAVIGATOR_MODIFY_PASSWORD_VERIFICATION";

//借款单详情页面
export const NAVIGATOR_LOAN_ORDER_DETAIL = "NAVIGATOR_LOAN_ORDER_DETAIL";

//借款单列表页面
export const NAVIGATOR_LOAN_ORDER_LIST = "NAVIGATOR_LOAN_ORDER_LIST";
export const RESET_LOAN_LIST = "RESET_LOAN_LIST";

//请选择城市页面
export const NAVIGATE_SELECT_CITY = "NAVIGATE_SELECT_CITY";

//新建借款单页面
export const NAVIGATE_NEW_LOAN_ORDER = "NAVIGATE_NEW_LOAN_ORDER";

//修改密码页面
export const NAVIGATOR_MODIFY_PASSWORD = "NAVIGATOR_MODIFY_PASSWORD";

//设置新密码页面
export const NAVIGATOR_CREATE_NEW_PASSWORD = "NAVIGATOR_CREATE_NEW_PASSWORD";

//我的通知页面
export const NAVIGATOR_MY_NOTICES = "NAVIGATOR_MY_NOTICES";

//返回登陆页面
export const BACK_LOGIN = "BACK_LOGIN";

//跳转去主页面
export const NAVIGATOR_MAINSCREEN = "NAVIGATOR_MAINSCREEN";

//跳转到新增报销单页面
export const NAVIGATOR_NEW_REIMBURSEMENT = "NAVIGATOR_NEW_REIMBURSEMENT";
export const RESET_NEW_REIMBURSEMENT = "RESET_NEW_REIMBURSEMENT";

//找回密码
export const NAVIGATOR_FIND_PASSWORD = "NAVIGATOR_FIND_PASSWORD";

//返回上个页面
export const BACK = "BACK";

//跳转去我的申请页面
export const NAVIGATOR_APPLICATION_LIST = "NAVIGATOR_APPLICATION_LIST";
export const RESET_APPLICATION_LIST = "RESET_APPLICATION_LIST";

//跳转去我的审批页面
export const NAVIGATOR_AUDIT_LIST = "NAVIGATOR_AUDIT_LIST";

//跳转去报销详情页面
export const NAVIGATOR_REIMBURSEMENT_DETAIL = "NAVIGATOR_REIMBURSEMENT_DETAIL";

//跳转去回复页
export const NAVIGATOR_REIMBURSEMENT_REPLY = "NAVIGATOR_REIMBURSEMENT_REPLY";

//跳转去票夹页面选取发票
export const NAVIGATOR_INVOICE_LIST = "NAVIGATOR_INVOICE_LIST";
export const RESET_INVOICE_LIST = "RESET_INVOICE_LIST";

//跳转去发票详情页面
export const NAVIGATOR_INVOICE_DETAIL = "NAVIGATOR_INVOICE_DETAIL";

//跳转去发票详情页面
export const NAVIGATOR_NEW_INVOICE = "NAVIGATOR_NEW_INVOICE";

//跳转去发票编辑页面
export const NAVIGATOR_EDIT_INVOICE = "NAVIGATOR_EDIT_INVOICE";

//跳转去扫码页面
export const NAVIGATOR_SCAN_QRCODE = "NAVIGATOR_SCAN_QRCODE";

//跳转去扫码失败页面
export const NAVIGATOR_SCAN_QRCODE_ERROR = "NAVIGATOR_SCAN_QRCODE_ERROR";

//跳转到添加发票页面
export const NAVIGATOR_ADD_INVOICE = "NAVIGATOR_ADD_INVOICE";

export const APP_CHANGE_STATE = "APP_CHANGE_STATE";
//登录
export const LOGIN_CHANGE_STATE = "LOGIN_CHANGE_STATE";

//首页
export const HOME_PAGE_CHANGE_STATE = "HOME_PAGE_CHANGE_STATE";
export const HOME_PAGE_LOAD_COUNT = "HOME_PAGE_LOAD_COUNT";

//新增报销单
export const INIT_NEW_REIMBURSEMENT = "INIT_NEW_REIMBURSEMENT";
export const SHOW_SELECT_REIM_TYPE = "SHOW_SELECT_REIM_TYPE";
export const CLOSE_MODALS = "CLOSE_MODALS";
export const SELECT_REIM_TYPE = "SELECT_REIM_TYPE";
export const ADD_INVOICE = "ADD_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const DELETE_DETAIL = "DELETE_DETAIL";
export const SHOW_ALERT = "SHOW_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";
export const ADD_NEW_EXPENSE_DETAIL = "ADD_NEW_EXPENSE_DETAIL";
export const DELETE_EXPENSE_DETAIL = "DELETE_EXPENSE_DETAIL";
export const NEW_REIMBURSEMENT_CHANGE_STATE = 'NEW_REIMBURSEMENT_CHANGE_STATE';
export const SELECTED_INVOICE_LIST = 'SELECTED_INVOICE_LIST';
export const EDIT_TO_NEW_REIMBURSEMENT_WITH_SELECTED_INVOICE_LIST = "EDIT_TO_NEW_REIMBURSEMENT_WITH_SELECTED_INVOICE_LIST";

//报销详情
export const REIMBURSEMENT_DETAIL_CHANGE_STATE = 'REIMBURSEMENT_DETAIL_CHANGE_STATE';

//发票列表
export const INVOICE_LIST_CHANGE_STATE = 'INVOICE_LIST_CHANGE_STATE';

//发票详情
export const INVOICE_DETAIL_CHANGE_STATE = 'INVOICE_DETAIL_CHANGE_STATE';
export const INIT_INVOICE_DETAIL = 'INIT_INVOICE_DETAIL';


//申请列表
export const REIMBURSEMENT_LIST_CHANGE_STATE = 'REIMBURSEMENT_LIST_CHANGE_STATE';
export const REIMBURSEMENT_LIST_LOAD_DATA = 'REIMBURSEMENT_LIST_LOAD_DATA';
export const REIMBURSEMENT_LIST_LOAD_APPLICATION_LIST_DATA = 'REIMBURSEMENT_LIST_LOAD_APPLICATION_LIST_DATA';

//审批列表
export const AUDIT_LIST_CHANGE_STATE = 'AUDIT_LIST_CHANGE_STATE';

//注册
export const NAVIGATOR_REGISTER_CHANGE_STATE = "NAVIGATOR_REGISTER_CHANGE_STATE";

//注册密码
export const NAVIGATOR_REGISTER_PASSWORD_CHANGE_STATE = "NAVIGATOR_REGISTER_PASSWORD_CHANGE_STATE";

//设置
export const SET_UP_CHANGE_STATE = "SET_UP_CHANGE_STATE";

//个人信息
export const PERSONAL_INFORMATION_CHANGE_STATE = "PERSONAL_INFORMATION_CHANGE_STATE";

//修改密码-手机验证
export const MODIFY_PASSWORD_VERIFICATION_CHANGE_STATE = "MODIFY_PASSWORD_VERIFICATION_CHANGE_STATE";

//修改密码-设置新密码
export const MODIFY_PASSWORD_CHANGE_STATE = "MODIFY_PASSWORD_CHANGE_STATE";

//找回密码-手机验证
export const FIND_PASSWORD_CHANGE_STATE = "FIND_PASSWORD_CHANGE_STATE";

//找回密码-创建新密码
export const CREATE_NEW_PASSWORD_CHANGE_STATE = "CREATE_NEW_PASSWORD_CHANGE_STATE";

//创建企业
export const OPEN_ENTERPRISE_CHANGE_STATE = "OPEN_ENTERPRISE_CHANGE_STATE";

//成功创建企业
export const SUCCESS_OPEN_ENTERPRISE_CHANGE_STATE = "SUCCESS_OPEN_ENTERPRISE_CHANGE_STATE";

//新增发票
export const NEW_INVOICE_CHANGE_STATE = 'NEW_INVOICE_CHANGE_STATE';
export const NEW_INVOICE_INIT_STATE = 'NEW_INVOICE_INIT_STATE';

//扫描二维码
export const SCAN_QRCODE_CHANGE_STATE = 'SCAN_QRCODE_CHANGE_STATE';
export const SCAN_QRCODE_INIT_STATE = 'SCAN_QRCODE_INIT_STATE';
export const SCAN_QRCODE_READ_QRCODE = 'SCAN_QRCODE_READ_QRCODE';

//报表
export const REPORT_CHANGE_STATE = 'REPORT_CHANGE_STATE';

//主界面
export const MAIN_SCREEN_CHANGE_STATE = 'MAIN_SCREEN_CHANGE_STATE';

//我的
export const MINE_CHANGE_STATE = "MINE_CHANGE_STATE";

//我的消息
export const MINE_NOTICES_STATE = "MINE_NOTICES_STATE";

//添加发票
export const ADD_INVOICE_STATE = "ADD_INVOICE_STATE";

//编辑发票
export const EDIT_INVOICE_STATE = "EDIT_INVOICE_STATE";
export const EDIT_INVOICE_INIT_STATE = "EDIT_INVOICE_INIT_STATE";

//回复页
export const COMMENT_REPLY_CHANGE_STATE = 'COMMENT_REPLY_CHANGE_STATE';

//HttpUtil
export const HTTP_UTIL_CHANGE_STATE = 'HTTP_UTIL_CHANGE_STATE';

//选择抄送人
export const SELECT_COPY_PERSON = "SELECT_COPY_PERSON";
export const SELECT_COPY_PERSON_INIT_DATA = "SELECT_COPY_PERSON_INIT_DATA";
export const SELECT_COPY_PERSON_CHANGE_STATE = "SELECT_COPY_PERSON_CHANGE_STATE";

//请选择城市
export const SELECT_CITY_CHANGE_STATE = 'SELECT_CITY_CHANGE_STATE';

//新建借款单
export const INIT_NEW_LOAN = 'INIT_NEW_LOAN';
export const NEW_LOAN_ORDER_CHANGE_STATE = 'NEW_LOAN_ORDER_CHANGE_STATE';
export const LOAN_ORDER_DETAIL_CHANGE_STATE = 'LOAN_ORDER_DETAIL_CHANGE_STATE';
export const LOAN_ORDER_LIST_CHANGE_STATE = 'LOAN_ORDER_LIST_CHANGE_STATE';

//成本中心--费用分摊
export const COST_SHARING = "COST_SHARING";
export const COST_SHARING_INIT_DATA = "COST_SHARING_INIT_DATA";
export const COST_SHARING_CHANGE_STATE = "COST_SHARING_CHANGE_STATE";

//选择核销借款
export const SELECT_WRITE_OFF_LOAN = "SELECT_WRITE_OFF_LOAN";
export const SELECT_WRITE_OFF_LOAN_CHANGE_STATE = "SELECT_WRITE_OFF_LOAN_CHANGE_STATE";
export const SELECT_WRITE_OFF_LOAN_INIT_DATA = "SELECT_WRITE_OFF_LOAN_INIT_DATA";

//选择出差申请
export const SELECT_TRAVEL_APPLY = "SELECT_TRAVEL_APPLY";
export const TRAVEL_APPLY_INIT_DATA = "TRAVEL_APPLY_INIT_DATA";
export const TRAVEL_APPLY_CHANGE_STATE = "TRAVEL_APPLY_CHANGE_STATE";

//新建差旅申请单
export const NEW_TRAVEL_APPLY = "NEW_TRAVEL_APPLY";
export const NEW_TRAVEL_APPLY_INIT_DATA = "NEW_TRAVEL_APPLY_INIT_DATA";
export const NEW_TRAVEL_APPLY_CHANGE_STATE = "NEW_TRAVEL_APPLY_CHANGE_STATE";

//差旅申请详情
export const TRAVEL_APPLY_DETAIL = "TRAVEL_APPLY_DETAIL";
export const TRAVEL_APPLY_DETAIL_CHANGE_STATE = "TRAVEL_APPLY_DETAIL_CHANGE_STATE";
export const TRAVEL_APPLY_DETAIL_INIT_DATA = "TRAVEL_APPLY_DETAIL_INIT_DATA";

//差旅申请列表
export const TRAVEL_APPLY_LIST = "TRAVEL_APPLY_LIST";
export const TRAVEL_APPLY_LIST_CHANGE_STATE = "TRAVEL_APPLY_LIST_CHANGE_STATE";
export const TRAVEL_APPLY_LIST_INIT_DATA = "TRAVEL_APPLY_LIST_INIT_DATA";
export const RESET_TRAVEL_APPLY_LIST = "RESET_TRAVEL_APPLY_LIST";


