#ifndef INCLUDED_BARCODE_TYPES_H                /* Has this file been included before?  */
#define INCLUDED_BARCODE_TYPES_H                /* No, remember it has been now         */


typedef enum 
{
BARCODE_TYPE_UNKNOWN = 0,
//¶þÎ¬Âë
BARCODE_TYPE_QR,
BARCODE_TYPE_CS,
BARCODE_TYPE_DM,
BARCODE_TYPE_PDF417,
BARCODE_TYPE_AZTEC,
//Ò»Î¬Âë
BARCODE_TYPE_UPCE,
BARCODE_TYPE_UPCA,
BARCODE_TYPE_EAN8,
BARCODE_TYPE_EAN13,
BARCODE_TYPE_CODE128,
BARCODE_TYPE_CODE39,
BARCODE_TYPE_ITF,
BARCODE_TYPE_RSS14,
BARCODE_TYPE_CODE93,
BARCODE_TYPE_CODABAR,
BARCODE_TYPE_MATRIX25,
BARCODE_TYPE_INDUSTRIAL25,   //Standard 2 of 5
}BARCODE_TYPE;


#endif
